import { Ionicons } from "@expo/vector-icons";
import React, { useState, useEffect } from "react";
import {
  FlatList,
  StyleSheet,
  Text,
  TextInput,
  TouchableOpacity,
  View,
  Image,
  ActivityIndicator,
  Alert,
} from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { LinearGradient } from "expo-linear-gradient";
import { colors, borders, typography } from "../styles";
import { useNavigation, useFocusEffect } from "@react-navigation/native";
import { NativeStackNavigationProp } from "@react-navigation/native-stack";
import { MainStackParamList } from "../navigation/MainStack";
import { useUserStore } from "../store/userStore";
import { getFriendRequests } from "../api/FriendApi";
import { addGroup } from "../api/Group";

interface Contact {
  id: string;
  name: string;
  userId: string;
  image?: string;
}

const FriendItem = ({
  item,
  isSelected,
  onToggle,
}: {
  item: Contact;
  isSelected: boolean;
  onToggle: (id: string) => void;
}) => {
  return (
    <TouchableOpacity
      activeOpacity={0.7}
      onPress={() => onToggle(item.id)}
      style={styles.friendItem}
    >
      <View style={styles.leftSection}>
        <View style={styles.avatarPlaceholder}>
          <Image
            source={{ uri: item.image || "https://postimg.cc/34y84VvN" }}
            style={styles.avatarImage}
          />
        </View>
        <View>
          <Text style={styles.friendName}>{item.name}</Text>
          <Text style={styles.friendId}>ID: {item.userId}</Text>
        </View>
      </View>

      <View style={styles.rightSection}>
        <View
          style={[
            styles.checkbox,
            isSelected && styles.checkboxSelected,
          ]}
        >
          {isSelected && (
            <Ionicons name="checkmark" size={18} color={colors.background.white} />
          )}
        </View>
      </View>
    </TouchableOpacity>
  );
};

export default function AddGroup() {
  const navigation = useNavigation<NativeStackNavigationProp<MainStackParamList>>();
  const { userId } = useUserStore();
  const [searchText, setSearchText] = useState("");
  const [selectedFriends, setSelectedFriends] = useState<string[]>([]);
  const [contacts, setContacts] = useState<Contact[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [isCreating, setIsCreating] = useState(false);
  const [groupName, setGroupName] = useState("");

  // Fetch friends when component mounts
  useFocusEffect(
    React.useCallback(() => {
      if (userId) {
        fetchFriends();
      }
    }, [userId])
  );

  const fetchFriends = async () => {
    if (!userId) {
      console.log('⚠️ No userId available');
      setIsLoading(false);
      return;
    }

    try {
      setIsLoading(true);
      const response = await getFriendRequests(userId, 2); // Get accepted friends (status=2)

      if (response && !response.error && response.response) {
        const requestFriends = response.response.request || [];
        const approveFriends = response.response.approve || [];

        const allFriends: Contact[] = [];

        // Friends where I sent the request
        requestFriends.forEach((friend: any) => {
          const friendUserId = friend.approve_id || friend.user_id || friend.id;
          allFriends.push({
            id: friend.list_id || friendUserId || String(Math.random()),
            name: friend.name || friendUserId || "未知用户",
            userId: friendUserId,
            image: friend.image,
          });
        });

        // Friends where I received the request
        approveFriends.forEach((friend: any) => {
          const friendUserId = friend.request_id || friend.user_id || friend.id;
          allFriends.push({
            id: friend.list_id || friendUserId || String(Math.random()),
            name: friend.name || friendUserId || "未知用户",
            userId: friendUserId,
            image: friend.image,
          });
        });

        console.log('✅ Loaded friends for group:', allFriends.length);
        setContacts(allFriends);
      }
    } catch (error) {
      console.error('❌ Error fetching friends:', error);
      Alert.alert('错误', '无法加载好友列表');
    } finally {
      setIsLoading(false);
    }
  };

  const toggleFriend = (id: string) => {
    setSelectedFriends((prev) => {
      const newSelected = prev.includes(id) ? prev.filter((fid) => fid !== id) : [...prev, id];

      // Auto-generate group name when selection changes
      if (newSelected.length > 0) {
        const selectedContacts = contacts.filter((contact) => newSelected.includes(contact.id));
        const autoGeneratedName = selectedContacts
          .map((contact) => contact.name)
          .slice(0, 3)
          .join("、") + (selectedContacts.length > 3 ? "..." : "");

        // Only update if user hasn't manually edited the name
        if (!groupName || prev.length === 0) {
          setGroupName(autoGeneratedName);
        }
      } else {
        setGroupName("");
      }

      return newSelected;
    });
  };

  const filteredData = contacts.filter((contact) =>
    contact.name.toLowerCase().includes(searchText.toLowerCase()) ||
    contact.userId.toLowerCase().includes(searchText.toLowerCase())
  );

  const handleCreateGroup = async () => {
    if (!userId) {
      Alert.alert('错误', '无法获取用户信息');
      return;
    }

    if (selectedFriends.length < 1) {
      Alert.alert('提示', '请至少选择一位好友');
      return;
    }

    if (!groupName.trim()) {
      Alert.alert('提示', '请输入群聊名称');
      return;
    }

    try {
      setIsCreating(true);

      // Get selected friend details
      const selectedContacts = contacts.filter((contact) =>
        selectedFriends.includes(contact.id)
      );

      // Prepare group members array
      const groupMembers = [
        { user_id: userId, isadmin: 2 }, // Creator is admin
        ...selectedContacts.map(contact => ({
          user_id: contact.userId,
          isadmin: 1 // Regular members
        }))
      ];

      console.log('📝 Creating group with:', {
        name: groupName.trim(),
        user_id: userId,
        members: groupMembers.length
      });

      const response = await addGroup({
        name: groupName.trim(),
        user_id: userId,
        image: "",
        group: groupMembers
      });

      console.log('✅ Group created:', response);

      if (response && !response.error) {
        const chatId = response.response;

        // Navigate to GroupScreen
        navigation.navigate("GroupScreen", {
          groupName: groupName.trim(),
          groupId: chatId,
          chatId: chatId,
        });
      } else {
        Alert.alert('错误', response?.message || '创建群聊失败');
      }
    } catch (error) {
      console.error('❌ Error creating group:', error);
      Alert.alert('错误', '创建群聊时发生错误');
    } finally {
      setIsCreating(false);
    }
  };

  if (isLoading) {
    return (
      <LinearGradient colors={colors.background.gradientYellow} style={styles.safeArea}>
        <SafeAreaView style={styles.container} edges={["top"]}>
          <View style={styles.header}>
            <TouchableOpacity
              style={styles.backButton}
              onPress={() => navigation.goBack()}
            >
              <Ionicons name="arrow-back" size={24} color={colors.text.primary} />
            </TouchableOpacity>
            <Text style={styles.headerTitle}>发起群聊</Text>
            <View style={styles.placeholder} />
          </View>
          <View style={styles.loadingContainer}>
            <ActivityIndicator size="large" color={colors.text.primary} />
          </View>
        </SafeAreaView>
      </LinearGradient>
    );
  }

  return (
    <LinearGradient colors={colors.background.gradientYellow} style={styles.safeArea}>
      <SafeAreaView style={styles.container} edges={["top"]}>
        {/* Header */}
        <View style={styles.header}>
          <TouchableOpacity
            style={styles.backButton}
            onPress={() => navigation.goBack()}
          >
            <Ionicons name="arrow-back" size={24} color={colors.text.primary} />
          </TouchableOpacity>
          <Text style={styles.headerTitle}>发起群聊</Text>
          <View style={styles.placeholder} />
        </View>

        {/* Search Bar */}
        <View style={styles.searchSection}>
          <View style={styles.searchBarContainer}>
            <Ionicons
              name="search"
              size={18}
              color={colors.text.lightGray}
              style={styles.searchIcon}
            />
            <TextInput
              placeholder="搜索"
              placeholderTextColor={colors.text.lightGray}
              style={styles.searchInput}
              value={searchText}
              onChangeText={setSearchText}
            />
            {searchText.length > 0 && (
              <TouchableOpacity onPress={() => setSearchText("")}>
                <Ionicons name="close-circle" size={20} color={colors.text.grayLight} />
              </TouchableOpacity>
            )}
          </View>
        </View>

        {selectedFriends.length > 0 && (
          <>
            <View style={styles.selectedCountContainer}>
              <Text style={styles.selectedCountText}>
                选择了 {selectedFriends.length} 人
              </Text>
            </View>

            {/* Group Name Input */}
            <View style={styles.groupNameContainer}>
              <Text style={styles.groupNameLabel}>群聊名称</Text>
              <TextInput
                style={styles.groupNameInput}
                placeholder="请输入群聊名称"
                placeholderTextColor={colors.text.lightGray}
                value={groupName}
                onChangeText={setGroupName}
                maxLength={50}
              />
            </View>
          </>
        )}

        {/* Friend List */}
        <FlatList
          data={filteredData}
          keyExtractor={(item) => item.id.toString()}
          renderItem={({ item }) => (
            <FriendItem
              item={item}
              isSelected={selectedFriends.includes(item.id)}
              onToggle={toggleFriend}
            />
          )}
          contentContainerStyle={styles.listContent}
          showsVerticalScrollIndicator={false}
        />

        {selectedFriends.length > 0 && (
          <View style={styles.createButtonContainer}>
            <TouchableOpacity
              style={[styles.createButton, isCreating && styles.createButtonDisabled]}
              onPress={handleCreateGroup}
              disabled={isCreating}
            >
              {isCreating ? (
                <ActivityIndicator size="small" color={colors.background.white} />
              ) : (
                <Text style={styles.createButtonText}>发起群聊</Text>
              )}
            </TouchableOpacity>
          </View>
        )}
      </SafeAreaView>
    </LinearGradient>
  );
}

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
  },
  container: {
    flex: 1,
  },
  header: {
    backgroundColor: colors.background.yellow,
    paddingTop: 16,
    paddingBottom: 12,
    paddingHorizontal: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  backButton: {
    width: 40,
    height: 40,
    justifyContent: "center",
    alignItems: "flex-start",
  },
  headerTitle: {
    fontSize: typography.fontSize16,
    fontWeight: typography.fontWeight600,
    color: colors.text.primary,
  },
  placeholder: {
    width: 40,
  },
  searchSection: {
    backgroundColor: colors.background.yellow,
    paddingHorizontal: 16,
    paddingBottom: 16,
  },
  searchBarContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.background.white,
    borderRadius: borders.radius8,
    paddingHorizontal: 12,
    height: 45,
  },
  searchIcon: {
    marginRight: 8,
  },
  searchInput: {
    flex: 1,
    fontSize: typography.fontSize15,
    color: colors.text.primary,
    padding: 0,
  },
  selectedCountContainer: {
    backgroundColor: colors.background.yellowPale,
    paddingVertical: 8,
    paddingHorizontal: 16,
    alignItems: "center",
  },
  selectedCountText: {
    fontSize: typography.fontSize14,
    color: colors.text.medium,
    fontWeight: typography.fontWeight500,
  },
  groupNameContainer: {
    backgroundColor: colors.background.white,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: borders.width1,
    borderBottomColor: colors.border.light,
  },
  groupNameLabel: {
    fontSize: typography.fontSize14,
    color: colors.text.medium,
    marginBottom: 8,
    fontWeight: typography.fontWeight500,
  },
  groupNameInput: {
    backgroundColor: colors.background.grayPale,
    borderRadius: borders.radius8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: typography.fontSize15,
    color: colors.text.primary,
  },
  listContent: {
    paddingTop: 10,
  },
  friendItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: colors.background.white,
    paddingHorizontal: 15,
    paddingVertical: 15,
    margin: 8,
    borderRadius: borders.radius10,
    borderBottomWidth: borders.width05,
    borderBottomColor: colors.border.whiteAlt,

    // iOS Shadow
    shadowColor: colors.shadow.default,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 8,

    // Android Shadow
    elevation: 5,
  },
  leftSection: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
  },
  avatarPlaceholder: {
    width: 48,
    height: 48,
    borderRadius: borders.radius8,
    backgroundColor: colors.functional.avatarPlaceholder,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
    overflow: "hidden",
  },
  avatarImage: {
    width: 48,
    height: 48,
  },
  friendName: {
    fontSize: typography.fontSize16,
    fontWeight: typography.fontWeight500,
    color: colors.text.primary,
    marginBottom: 2,
  },
  friendId: {
    fontSize: typography.fontSize12,
    color: colors.text.grayLight,
  },
  rightSection: {
    marginLeft: 12,
  },
  checkbox: {
    width: 24,
    height: 24,
    borderRadius: borders.radius4,
    borderWidth: 2,
    borderColor: colors.border.gray,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colors.background.white,
  },
  checkboxSelected: {
    backgroundColor: colors.functional.greenSuccess,
    borderColor: colors.functional.greenSuccess,
  },
  createButtonContainer: {
    padding: 16,
    backgroundColor: colors.background.white,
    borderTopWidth: borders.width1,
    borderTopColor: colors.border.light,
  },
  createButton: {
    backgroundColor: colors.functional.greenSuccess,
    paddingVertical: 14,
    borderRadius: borders.radius8,
    alignItems: "center",
  },
  createButtonText: {
    fontSize: typography.fontSize16,
    fontWeight: typography.fontWeight600,
    color: colors.background.white,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  createButtonDisabled: {
    opacity: 0.6,
  },
});